"use strict";
(function () {
 const KEY="campusLostFoundItems", OWNER="campusLostFoundPublisherId", TEST_OWNER="browser-test";
 const frame=document.getElementById("appFrame"), run=document.getElementById("runTests"), summary=document.getElementById("summary"), results=document.getElementById("results"), details=document.getElementById("details");
 const oldData=localStorage.getItem(KEY), oldOwner=localStorage.getItem(OWNER);
 const base=[
  {id:1,publisherId:TEST_OWNER,title:"黑色校园卡",type:"寻物",location:"第一教学楼",date:"2026-10-06",description:"遗失黑色校园卡",contact:"test@example.com",status:"待处理"},
  {id:2,publisherId:TEST_OWNER,title:"蓝色水杯",type:"招领",location:"图书馆",date:"2026-10-05",description:"捡到蓝色水杯",contact:"test@example.com",status:"待处理"},
  {id:3,publisherId:"other",title:"黑色钥匙",type:"寻物",location:"学生宿舍区",date:"2026-10-04",description:"遗失一串钥匙",contact:"other@example.com",status:"待处理"},
  {id:4,publisherId:TEST_OWNER,title:"白色耳机",type:"招领",location:"食堂",date:"2026-10-03",description:"捡到耳机",contact:"test@example.com",status:"待处理"}];
 const clone=x=>JSON.parse(JSON.stringify(x)), saved=()=>JSON.parse(localStorage.getItem(KEY)||"[]");
 const assert=(x,m)=>{if(!x)throw Error(m||"断言失败")};
 async function load(items){localStorage.setItem(KEY,JSON.stringify(clone(items)));localStorage.setItem(OWNER,TEST_OWNER);return new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error("加载超时")),10000);frame.onload=()=>{clearTimeout(t);const w=frame.contentWindow;w.alert=()=>{};w.confirm=()=>true;setTimeout(()=>resolve(w),100)};frame.src="../index.html?test="+Date.now()})}
 async function caseRun(name,fn){try{await fn();const li=document.createElement("li");li.className="pass";li.textContent="✅ "+name+"：通过";results.appendChild(li);return true}catch(e){const li=document.createElement("li");li.className="fail";li.textContent="❌ "+name+"："+e.message;results.appendChild(li);details.textContent+=name+"\n"+(e.stack||e.message)+"\n\n";return false}}
 async function all(){run.disabled=true;results.innerHTML="";details.textContent="";let p=0,f=0;const go=async(n,fn)=>{(await caseRun(n,fn))?p++:f++};try{
  await go("测试1：首页显示4条",async()=>{const d=(await load(base)).document;assert(d.querySelectorAll("#itemList .item-card").length===4,"数量错误")});
  await go("测试2：关键词搜索",async()=>{const d=(await load(base)).document;d.getElementById("searchInput").value="图书馆";d.getElementById("searchBtn").click();assert(d.querySelectorAll("#itemList .item-card").length===1,"搜索错误")});
  await go("测试3：招领筛选",async()=>{const d=(await load(base)).document;d.querySelector('[data-type="招领"]').click();assert(d.querySelectorAll("#itemList .item-card").length===2,"筛选错误")});
  await go("测试4：无结果提示",async()=>{const d=(await load(base)).document;d.getElementById("searchInput").value="不存在";d.getElementById("searchBtn").click();assert(d.querySelector(".empty-state"),"缺少提示")});
  await go("测试5：有效发布",async()=>{const d=(await load(base)).document;d.getElementById("publishNavBtn").click();["itemTitle","itemLocation","itemDate","itemDescription","itemContact"].forEach((id,i)=>d.getElementById(id).value=["新物品","图书馆","2026-10-09","描述","new@example.com"][i]);d.getElementById("publishForm").requestSubmit();assert(!d.getElementById("successPage").hidden,"发布失败")});
  await go("测试6：空联系方式禁止发布",async()=>{const d=(await load(base)).document;d.getElementById("publishNavBtn").click();["itemTitle","itemLocation","itemDate","itemDescription","itemContact"].forEach((id,i)=>d.getElementById(id).value=["无联系方式","图书馆","2026-10-09","描述","   "][i]);d.getElementById("publishForm").requestSubmit();assert(d.getElementById("successPage").hidden,"错误发布")});
  await go("测试7：独立编辑页保存",async()=>{const d=(await load(base)).document;d.getElementById("mineNavBtn").click();d.querySelector('[data-action="edit"][data-id="1"]').click();assert(!d.getElementById("editPage").hidden,"编辑页未打开");d.getElementById("editTitle").value="修改校园卡";d.getElementById("editContact").value="updated@example.com";d.getElementById("editForm").requestSubmit();assert(saved()[0].title==="修改校园卡","编辑未保存")});
  await go("测试8：取消编辑不保存",async()=>{const d=(await load(base)).document;d.getElementById("mineNavBtn").click();d.querySelector('[data-action="edit"][data-id="1"]').click();d.getElementById("editTitle").value="不应保存";d.getElementById("cancelEditBtn").click();assert(saved()[0].title==="黑色校园卡","取消仍保存")});
  await go("测试9：状态更新显示独立弹窗",async()=>{const d=(await load(base)).document;d.getElementById("mineNavBtn").click();d.querySelector('[data-action="found"][data-id="1"]').click();assert(saved()[0].status==="已找到","状态错误");const modal=d.getElementById("appModal");assert(!modal.hidden,"状态弹窗未显示");assert(d.getElementById("appModalMessage").textContent.includes("已找到"),"弹窗内容错误");d.getElementById("appModalClose").click();assert(modal.hidden,"确定后弹窗未关闭")});
  await go("测试10：重复标记提示显示独立弹窗",async()=>{const d=(await load(base)).document;d.getElementById("mineNavBtn").click();const button=d.querySelector('[data-action="found"][data-id="2"]');button.click();assert(saved().find(x=>x.id===2).status==="已归还","状态错误");d.getElementById("appModalClose").click();button.click();const modal=d.getElementById("appModal");assert(!modal.hidden,"重复标记弹窗未显示");assert(d.getElementById("appModalTitle").textContent==="状态提示","弹窗标题错误");assert(d.getElementById("appModalMessage").textContent.includes("已归还"),"弹窗内容错误");d.getElementById("appModalClose").click();assert(modal.hidden,"确定后弹窗未关闭")});
 }finally{oldData===null?localStorage.removeItem(KEY):localStorage.setItem(KEY,oldData);oldOwner===null?localStorage.removeItem(OWNER):localStorage.setItem(OWNER,oldOwner);summary.textContent="测试结束：通过 "+p+" 项，失败 "+f+" 项。";run.disabled=false}}
 run.addEventListener("click",all);
})();